// Generates shared/src/abis.ts and shared/src/deployments.ts from Foundry output.
// Run after `forge build` and after every deployment: `npm run gen`.
import { readFileSync, writeFileSync, readdirSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const out = join(root, "contracts", "out");
const shared = join(root, "shared", "src");

const contracts = ["LaunchFactory", "FeeHook", "LaunchRouter", "LaunchToken"];
let abis = "// AUTO-GENERATED by scripts/gen-shared.mjs — do not edit.\n\n";
for (const name of contracts) {
  const file = join(out, `${name}.sol`, `${name}.json`);
  if (!existsSync(file)) throw new Error(`Missing ${file}. Run \`forge build\` in contracts/ first.`);
  const { abi } = JSON.parse(readFileSync(file, "utf8"));
  const id = name.charAt(0).toLowerCase() + name.slice(1);
  abis += `export const ${id}Abi = ${JSON.stringify(abi, null, 2)} as const;\n\n`;
}
writeFileSync(join(shared, "abis.ts"), abis);

const depDir = join(root, "contracts", "deployments");
const deployments = {};
for (const f of existsSync(depDir) ? readdirSync(depDir) : []) {
  if (!f.endsWith(".json")) continue;
  const d = JSON.parse(readFileSync(join(depDir, f), "utf8"));
  deployments[d.chainId] = d;
}
const ts =
  "// AUTO-GENERATED by scripts/gen-shared.mjs — do not edit.\n\n" +
  "export type Deployment = {\n  name: string;\n  chainId: number;\n  factory: `0x${string}`;\n  hook: `0x${string}`;\n  router: `0x${string}`;\n  poolManager: `0x${string}`;\n  permit2: `0x${string}`;\n  startBlock: number;\n};\n\n" +
  `export const deployments: Record<number, Deployment> = ${JSON.stringify(deployments, null, 2)};\n`;
writeFileSync(join(shared, "deployments.ts"), ts);

console.log(`Wrote ABIs for ${contracts.join(", ")} and ${Object.keys(deployments).length} deployment(s).`);
