// AUTO-GENERATED by scripts/gen-shared.mjs — do not edit.

export type Deployment = {
  name: string;
  chainId: number;
  factory: `0x${string}`;
  hook: `0x${string}`;
  router: `0x${string}`;
  poolManager: `0x${string}`;
  permit2: `0x${string}`;
  startBlock: number;
};

export const deployments: Record<number, Deployment> = {
  "1337": {
    "chainId": 1337,
    "factory": "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9",
    "hook": "0x3D9317EADAE53fFc8C87F8A47b12D6E0E17fe0Cc",
    "name": "local",
    "permit2": "0x000000000022D473030F116dDEE9F6B43aC78BA3",
    "poolManager": "0x5FbDB2315678afecb367f032d93F642f64180aa3",
    "router": "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0",
    "startBlock": 7
  },
  "84532": {
    "chainId": 84532,
    "factory": "0xE652dF0F32Cb6120B5368836C01c275D96B71ba4",
    "hook": "0xdE08e873CB3E54254734CebbB4eBc43a2F6ea0CC",
    "name": "baseSepolia",
    "permit2": "0x000000000022D473030F116dDEE9F6B43aC78BA3",
    "poolManager": "0x05E73354cFDd6745C338b50BcFDfA3Aa6fA03408",
    "router": "0xe2c5c09b5DC03A5D138e2C8541D129C06f22b983",
    "startBlock": 47664768
  }
};
